Comment機能の追加
tatsukishiga/board pull request #5
Opened 2019-03-16 07:28 UTC by tatsukishiga

１，モデルの作成
２，モデルにバリデーションの追加
３，DB側にバリデーション追加
４，アソシエーションの追加

2019-03-24 02:23 UTC, ArakawaShintaro commented on app/controllers/comments_controller.rb
> +    @comment.save
保存に失敗することもあるので、その処理はしておきましょう

2019-03-24 02:23 UTC, ArakawaShintaro commented on app/controllers/comments_controller.rb
> +    redirect_to("/topics")
何回も言いますが、名前付きパスで！

2019-03-24 02:25 UTC, ArakawaShintaro commented on app/controllers/comments_controller.rb
> +    @comment = Comment.new(
これも前回言いましたが

```
@current_user.comments.new(~~~)
```

とかでuser_idがセットされた状態になります

2019-03-24 02:25 UTC, ArakawaShintaro commented on app/controllers/comments_controller.rb
> +class CommentsController < ApplicationController
ログイン、未ログインは考慮してます？

2019-03-24 02:25 UTC, ArakawaShintaro commented on app/controllers/comments_controller.rb
> +    @comment.update(content: params[:comment][:content])
ここも同じことしています

2019-03-24 14:14 UTC, tatsukishiga commented on app/controllers/comments_controller.rb
> +    @comment.save
こちらrenderを使用して、失敗時の処理をしたいのですが、検証中です。
相談の詳細をSlackの方で送らさせてもらってます。

2019-03-24 14:15 UTC, tatsukishiga commented on app/controllers/comments_controller.rb
> +    redirect_to("/topics")
修正しました。

2019-03-24 14:15 UTC, tatsukishiga commented on app/controllers/comments_controller.rb
> +    @comment = Comment.new(
修正しました

2019-03-24 14:16 UTC, tatsukishiga commented on app/controllers/comments_controller.rb
> +class CommentsController < ApplicationController
ログイン時のみ可能、またそのコメントの投稿者でないと編集出来ないようにしました。

2019-03-24 14:17 UTC, tatsukishiga commented on app/controllers/comments_controller.rb
> +    @comment.update(content: params[:comment][:content])
重複を削除しました。

2019-03-27 02:48 UTC, ArakawaShintaro requested changes

2019-03-27 02:48 UTC, ArakawaShintaro commented on app/controllers/comments_controller.rb
> +      flash[:notice] = "投稿に失敗しました。投稿が空白または、140字を超えています。"
投稿が空白または、140字を超えています
そのエラーとは限らなくないですかね？

2019-03-27 02:48 UTC, ArakawaShintaro commented on app/controllers/comments_controller.rb
> +      return
returnいりますか？

2019-03-27 02:48 UTC, ArakawaShintaro commented on app/controllers/comments_controller.rb
> +    @comment = Comment.find_by(id: params[:id])
ensure_correct_userの部分ですが

@comment.user_id == current_user.id
で、できそうです

2019-03-27 03:46 UTC, tatsukishiga commented on app/controllers/comments_controller.rb
> +      flash[:notice] = "投稿に失敗しました。投稿が空白または、140字を超えています。"
確かに、それ以外のエラーである可能性もあります。
エラーメッセージの表示方法として
ビューに書くエラーフルメッセージを
redirectの方でも試したのですが、
エラーが出てしまい、最終的に
こちらのコードを書きました。
今までは
仕組みとして、送られてきたフォームが
falseだった場合にエラー文が格納され
renderでそのまま表示しているという認識だったのですが、
redirectではエラーメソッドは
使用できないでしょうか？

2019-03-27 03:47 UTC, tatsukishiga commented on app/controllers/comments_controller.rb
> +      return
不要です。修正します！

2019-03-27 03:48 UTC, tatsukishiga commented on app/controllers/comments_controller.rb
> +    @comment = Comment.find_by(id: params[:id])
なるほどです！修正します！

2019-03-27 04:18 UTC, ArakawaShintaro commented on app/controllers/comments_controller.rb
> +      flash[:notice] = "投稿に失敗しました。投稿が空白または、140字を超えています。"
errorsに格納してrenderでエラーメッセージを表示させてあげるのがいいかな、と思います

2019-03-27 04:40 UTC, tatsukishiga commented on app/controllers/comments_controller.rb
> +      flash[:notice] = "投稿に失敗しました。投稿が空白または、140字を超えています。"
はい！そちらで、検証します！

2019-03-31 09:46 UTC, ArakawaShintaro commented on app/controllers/comments_controller.rb
> +    end
```ruby
if @comment.user_id != @current_user.id
  flash[:notice] = "権限がありません"
  redirect_to(topics_path)
end
```

2019-03-31 09:46 UTC, ArakawaShintaro commented on app/controllers/comments_controller.rb
> +    end
private以下に追記

2019-03-31 16:01 UTC, tatsukishiga commented on app/controllers/comments_controller.rb
> +    end
修正しました。

2019-03-31 16:01 UTC, tatsukishiga commented on app/controllers/comments_controller.rb
> +    @comment = Comment.find_by(id: params[:id])
完了してます

2019-03-31 16:01 UTC, tatsukishiga commented on app/controllers/comments_controller.rb
> +      return
完了してます

2019-03-31 16:01 UTC, tatsukishiga commented on app/controllers/comments_controller.rb
> +      flash[:notice] = "投稿に失敗しました。投稿が空白または、140字を超えています。"
完了してます

2019-03-31 16:02 UTC, tatsukishiga commented on app/controllers/comments_controller.rb
> +    @comment.save
完了してます

2019-04-01 05:09 UTC, ArakawaShintaro approved these changes
OK

2019-04-01 10:42 UTC, merged